// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds(id,create_at,update_at,user_id,name,url)
VALUES($1,$2,$3,$4,$5,$6)
RETURNING id, create_at, update_at, user_id, name, url
`

type CreateFeedParams struct {
	ID       uuid.UUID
	CreateAt time.Time
	UpdateAt time.Time
	UserID   uuid.NullUUID
	Name     string
	Url      string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.CreateAt,
		arg.UpdateAt,
		arg.UserID,
		arg.Name,
		arg.Url,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreateAt,
		&i.UpdateAt,
		&i.UserID,
		&i.Name,
		&i.Url,
	)
	return i, err
}
