// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feed_follow.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one

INSERT INTO feed_follow(id,create_at,update_at,user_id,feed_id)
VALUES($1,$2,$3,$4,$5)
RETURNING id, create_at, update_at, user_id, feed_id
`

type CreateFeedFollowParams struct {
	ID       uuid.UUID
	CreateAt time.Time
	UpdateAt time.Time
	UserID   uuid.UUID
	FeedID   uuid.UUID
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.CreateAt,
		arg.UpdateAt,
		arg.UserID,
		arg.FeedID,
	)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.CreateAt,
		&i.UpdateAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}
