// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID            uuid.UUID
	CreateAt      time.Time
	UpdateAt      time.Time
	UserID        uuid.UUID
	Name          string
	Url           string
	LastFetchedAt sql.NullTime
}

type FeedFollow struct {
	ID       uuid.UUID
	CreateAt time.Time
	UpdateAt time.Time
	UserID   uuid.UUID
	FeedID   uuid.UUID
}

type User struct {
	ID       uuid.UUID
	CreateAt time.Time
	UpdateAt time.Time
	Name     string
	ApiKey   string
}
